/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package radiomanagerclient

type BroadcastEpgDay struct {

	Day string `json:"day,omitempty"`

	Results []BroadcastEpgResult `json:"results"`
}
