/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package radiomanagerclient

type BroadcastEpgRelations struct {

	Items BroadcastRelationsItems `json:"items,omitempty"`

	Blocks BroadcastRelationsBlocks `json:"blocks,omitempty"`

	Program BlockRelationsProgram `json:"program,omitempty"`

	Tags BroadcastRelationsTags `json:"tags,omitempty"`

	Presenters []PresenterEpgResult `json:"presenters,omitempty"`

	ModelType BroadcastRelationsModelType `json:"model_type,omitempty"`
}
