/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package radiomanagerclient

import (
	"time"
)

type BroadcastEpgDay struct {

	Day time.Time `json:"day,omitempty"`

	Results []BroadcastEpgResult `json:"results"`
}
