/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package radiomanagerclient

import (
	"time"
)

type CampaignDataInput struct {

	ModelTypeId int64 `json:"model_type_id"`

	FieldValues []interface{} `json:"field_values,omitempty"`

	Title string `json:"title,omitempty"`

	Start time.Time `json:"start"`

	Stop time.Time `json:"stop"`

	Recommended bool `json:"recommended,omitempty"`

	Description string `json:"description,omitempty"`
}
