/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package radiomanagerclient

import (
	"time"
)

type Data1 struct {

	Start time.Time `json:"start,omitempty"`

	Items []ImportItem `json:"items,omitempty"`
}
