/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package radiomanagerclient

import (
	"time"
)

type Data2 struct {

	Start time.Time `json:"start,omitempty"`

	AllowPlaylistPast int32 `json:"allow_playlist_past,omitempty"`

	BeforeId int32 `json:"before_id,omitempty"`

	PreviousId int32 `json:"previous_id,omitempty"`

	Items []ImportItem `json:"items,omitempty"`
}
