/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package radiomanagerclient

type InviteUserData struct {

	Email string `json:"email"`

	RoleIds []int32 `json:"role_ids"`
}
