/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package radiomanagerclient

type InviteUserData struct {

	Email string `json:"email"`

	RoleIds []int32 `json:"role_ids"`
}
