/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package radiomanagerclient

type ItemInputOnly struct {

	PreviousId int64 `json:"_previous_id,omitempty"`

	BeforeId int64 `json:"_before_id,omitempty"`

	Contacts []int32 `json:"contacts,omitempty"`

	Tags []int32 `json:"tags,omitempty"`
}
