/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package radiomanagerclient
// InlineObject3 struct for InlineObject3
type InlineObject3 struct {
	Id int32 `json:"id,omitempty"`
}
