/*
RadioManager

This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

API version: 2.0
Contact: support@pluxbox.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package radiomanagerclient

import (
	"encoding/json"
	"time"
)

// Broadcast struct for Broadcast
type Broadcast struct {
	ProgramId *int64 `json:"program_id,omitempty"`
	ModelTypeId *int64 `json:"model_type_id,omitempty"`
	StationId *int64 `json:"station_id,omitempty"`
	FieldValues map[string]interface{} `json:"field_values,omitempty"`
	Title *string `json:"title,omitempty"`
	Start *time.Time `json:"start,omitempty"`
	Stop *time.Time `json:"stop,omitempty"`
	GenreId *int64 `json:"genre_id,omitempty"`
	Description *string `json:"description,omitempty"`
	ShortName *string `json:"short_name,omitempty"`
	MediumName *string `json:"medium_name,omitempty"`
	Website *string `json:"website,omitempty"`
	Email *string `json:"email,omitempty"`
	Recommended *bool `json:"recommended,omitempty"`
	Language *string `json:"language,omitempty"`
	Published *bool `json:"published,omitempty"`
	RepetitionUid *string `json:"repetition_uid,omitempty"`
	RepetitionType *string `json:"repetition_type,omitempty"`
	RepetitionEnd *time.Time `json:"repetition_end,omitempty"`
	RepetitionStart *time.Time `json:"repetition_start,omitempty"`
	RepetitionDays *string `json:"repetition_days,omitempty"`
	PtyCodeId *int64 `json:"pty_code_id,omitempty"`
	PlannedInEpg *int32 `json:"planned_in_epg,omitempty"`
	GroupId *int64 `json:"group_id,omitempty"`
}

// NewBroadcast instantiates a new Broadcast object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBroadcast() *Broadcast {
	this := Broadcast{}
	return &this
}

// NewBroadcastWithDefaults instantiates a new Broadcast object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBroadcastWithDefaults() *Broadcast {
	this := Broadcast{}
	return &this
}

// GetProgramId returns the ProgramId field value if set, zero value otherwise.
func (o *Broadcast) GetProgramId() int64 {
	if o == nil || isNil(o.ProgramId) {
		var ret int64
		return ret
	}
	return *o.ProgramId
}

// GetProgramIdOk returns a tuple with the ProgramId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetProgramIdOk() (*int64, bool) {
	if o == nil || isNil(o.ProgramId) {
    return nil, false
	}
	return o.ProgramId, true
}

// HasProgramId returns a boolean if a field has been set.
func (o *Broadcast) HasProgramId() bool {
	if o != nil && !isNil(o.ProgramId) {
		return true
	}

	return false
}

// SetProgramId gets a reference to the given int64 and assigns it to the ProgramId field.
func (o *Broadcast) SetProgramId(v int64) {
	o.ProgramId = &v
}

// GetModelTypeId returns the ModelTypeId field value if set, zero value otherwise.
func (o *Broadcast) GetModelTypeId() int64 {
	if o == nil || isNil(o.ModelTypeId) {
		var ret int64
		return ret
	}
	return *o.ModelTypeId
}

// GetModelTypeIdOk returns a tuple with the ModelTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetModelTypeIdOk() (*int64, bool) {
	if o == nil || isNil(o.ModelTypeId) {
    return nil, false
	}
	return o.ModelTypeId, true
}

// HasModelTypeId returns a boolean if a field has been set.
func (o *Broadcast) HasModelTypeId() bool {
	if o != nil && !isNil(o.ModelTypeId) {
		return true
	}

	return false
}

// SetModelTypeId gets a reference to the given int64 and assigns it to the ModelTypeId field.
func (o *Broadcast) SetModelTypeId(v int64) {
	o.ModelTypeId = &v
}

// GetStationId returns the StationId field value if set, zero value otherwise.
func (o *Broadcast) GetStationId() int64 {
	if o == nil || isNil(o.StationId) {
		var ret int64
		return ret
	}
	return *o.StationId
}

// GetStationIdOk returns a tuple with the StationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetStationIdOk() (*int64, bool) {
	if o == nil || isNil(o.StationId) {
    return nil, false
	}
	return o.StationId, true
}

// HasStationId returns a boolean if a field has been set.
func (o *Broadcast) HasStationId() bool {
	if o != nil && !isNil(o.StationId) {
		return true
	}

	return false
}

// SetStationId gets a reference to the given int64 and assigns it to the StationId field.
func (o *Broadcast) SetStationId(v int64) {
	o.StationId = &v
}

// GetFieldValues returns the FieldValues field value if set, zero value otherwise.
func (o *Broadcast) GetFieldValues() map[string]interface{} {
	if o == nil || isNil(o.FieldValues) {
		var ret map[string]interface{}
		return ret
	}
	return o.FieldValues
}

// GetFieldValuesOk returns a tuple with the FieldValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetFieldValuesOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.FieldValues) {
    return map[string]interface{}{}, false
	}
	return o.FieldValues, true
}

// HasFieldValues returns a boolean if a field has been set.
func (o *Broadcast) HasFieldValues() bool {
	if o != nil && !isNil(o.FieldValues) {
		return true
	}

	return false
}

// SetFieldValues gets a reference to the given map[string]interface{} and assigns it to the FieldValues field.
func (o *Broadcast) SetFieldValues(v map[string]interface{}) {
	o.FieldValues = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *Broadcast) GetTitle() string {
	if o == nil || isNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetTitleOk() (*string, bool) {
	if o == nil || isNil(o.Title) {
    return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *Broadcast) HasTitle() bool {
	if o != nil && !isNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *Broadcast) SetTitle(v string) {
	o.Title = &v
}

// GetStart returns the Start field value if set, zero value otherwise.
func (o *Broadcast) GetStart() time.Time {
	if o == nil || isNil(o.Start) {
		var ret time.Time
		return ret
	}
	return *o.Start
}

// GetStartOk returns a tuple with the Start field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetStartOk() (*time.Time, bool) {
	if o == nil || isNil(o.Start) {
    return nil, false
	}
	return o.Start, true
}

// HasStart returns a boolean if a field has been set.
func (o *Broadcast) HasStart() bool {
	if o != nil && !isNil(o.Start) {
		return true
	}

	return false
}

// SetStart gets a reference to the given time.Time and assigns it to the Start field.
func (o *Broadcast) SetStart(v time.Time) {
	o.Start = &v
}

// GetStop returns the Stop field value if set, zero value otherwise.
func (o *Broadcast) GetStop() time.Time {
	if o == nil || isNil(o.Stop) {
		var ret time.Time
		return ret
	}
	return *o.Stop
}

// GetStopOk returns a tuple with the Stop field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetStopOk() (*time.Time, bool) {
	if o == nil || isNil(o.Stop) {
    return nil, false
	}
	return o.Stop, true
}

// HasStop returns a boolean if a field has been set.
func (o *Broadcast) HasStop() bool {
	if o != nil && !isNil(o.Stop) {
		return true
	}

	return false
}

// SetStop gets a reference to the given time.Time and assigns it to the Stop field.
func (o *Broadcast) SetStop(v time.Time) {
	o.Stop = &v
}

// GetGenreId returns the GenreId field value if set, zero value otherwise.
func (o *Broadcast) GetGenreId() int64 {
	if o == nil || isNil(o.GenreId) {
		var ret int64
		return ret
	}
	return *o.GenreId
}

// GetGenreIdOk returns a tuple with the GenreId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetGenreIdOk() (*int64, bool) {
	if o == nil || isNil(o.GenreId) {
    return nil, false
	}
	return o.GenreId, true
}

// HasGenreId returns a boolean if a field has been set.
func (o *Broadcast) HasGenreId() bool {
	if o != nil && !isNil(o.GenreId) {
		return true
	}

	return false
}

// SetGenreId gets a reference to the given int64 and assigns it to the GenreId field.
func (o *Broadcast) SetGenreId(v int64) {
	o.GenreId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *Broadcast) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *Broadcast) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *Broadcast) SetDescription(v string) {
	o.Description = &v
}

// GetShortName returns the ShortName field value if set, zero value otherwise.
func (o *Broadcast) GetShortName() string {
	if o == nil || isNil(o.ShortName) {
		var ret string
		return ret
	}
	return *o.ShortName
}

// GetShortNameOk returns a tuple with the ShortName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetShortNameOk() (*string, bool) {
	if o == nil || isNil(o.ShortName) {
    return nil, false
	}
	return o.ShortName, true
}

// HasShortName returns a boolean if a field has been set.
func (o *Broadcast) HasShortName() bool {
	if o != nil && !isNil(o.ShortName) {
		return true
	}

	return false
}

// SetShortName gets a reference to the given string and assigns it to the ShortName field.
func (o *Broadcast) SetShortName(v string) {
	o.ShortName = &v
}

// GetMediumName returns the MediumName field value if set, zero value otherwise.
func (o *Broadcast) GetMediumName() string {
	if o == nil || isNil(o.MediumName) {
		var ret string
		return ret
	}
	return *o.MediumName
}

// GetMediumNameOk returns a tuple with the MediumName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetMediumNameOk() (*string, bool) {
	if o == nil || isNil(o.MediumName) {
    return nil, false
	}
	return o.MediumName, true
}

// HasMediumName returns a boolean if a field has been set.
func (o *Broadcast) HasMediumName() bool {
	if o != nil && !isNil(o.MediumName) {
		return true
	}

	return false
}

// SetMediumName gets a reference to the given string and assigns it to the MediumName field.
func (o *Broadcast) SetMediumName(v string) {
	o.MediumName = &v
}

// GetWebsite returns the Website field value if set, zero value otherwise.
func (o *Broadcast) GetWebsite() string {
	if o == nil || isNil(o.Website) {
		var ret string
		return ret
	}
	return *o.Website
}

// GetWebsiteOk returns a tuple with the Website field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetWebsiteOk() (*string, bool) {
	if o == nil || isNil(o.Website) {
    return nil, false
	}
	return o.Website, true
}

// HasWebsite returns a boolean if a field has been set.
func (o *Broadcast) HasWebsite() bool {
	if o != nil && !isNil(o.Website) {
		return true
	}

	return false
}

// SetWebsite gets a reference to the given string and assigns it to the Website field.
func (o *Broadcast) SetWebsite(v string) {
	o.Website = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *Broadcast) GetEmail() string {
	if o == nil || isNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetEmailOk() (*string, bool) {
	if o == nil || isNil(o.Email) {
    return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *Broadcast) HasEmail() bool {
	if o != nil && !isNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *Broadcast) SetEmail(v string) {
	o.Email = &v
}

// GetRecommended returns the Recommended field value if set, zero value otherwise.
func (o *Broadcast) GetRecommended() bool {
	if o == nil || isNil(o.Recommended) {
		var ret bool
		return ret
	}
	return *o.Recommended
}

// GetRecommendedOk returns a tuple with the Recommended field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetRecommendedOk() (*bool, bool) {
	if o == nil || isNil(o.Recommended) {
    return nil, false
	}
	return o.Recommended, true
}

// HasRecommended returns a boolean if a field has been set.
func (o *Broadcast) HasRecommended() bool {
	if o != nil && !isNil(o.Recommended) {
		return true
	}

	return false
}

// SetRecommended gets a reference to the given bool and assigns it to the Recommended field.
func (o *Broadcast) SetRecommended(v bool) {
	o.Recommended = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *Broadcast) GetLanguage() string {
	if o == nil || isNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetLanguageOk() (*string, bool) {
	if o == nil || isNil(o.Language) {
    return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *Broadcast) HasLanguage() bool {
	if o != nil && !isNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *Broadcast) SetLanguage(v string) {
	o.Language = &v
}

// GetPublished returns the Published field value if set, zero value otherwise.
func (o *Broadcast) GetPublished() bool {
	if o == nil || isNil(o.Published) {
		var ret bool
		return ret
	}
	return *o.Published
}

// GetPublishedOk returns a tuple with the Published field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetPublishedOk() (*bool, bool) {
	if o == nil || isNil(o.Published) {
    return nil, false
	}
	return o.Published, true
}

// HasPublished returns a boolean if a field has been set.
func (o *Broadcast) HasPublished() bool {
	if o != nil && !isNil(o.Published) {
		return true
	}

	return false
}

// SetPublished gets a reference to the given bool and assigns it to the Published field.
func (o *Broadcast) SetPublished(v bool) {
	o.Published = &v
}

// GetRepetitionUid returns the RepetitionUid field value if set, zero value otherwise.
func (o *Broadcast) GetRepetitionUid() string {
	if o == nil || isNil(o.RepetitionUid) {
		var ret string
		return ret
	}
	return *o.RepetitionUid
}

// GetRepetitionUidOk returns a tuple with the RepetitionUid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetRepetitionUidOk() (*string, bool) {
	if o == nil || isNil(o.RepetitionUid) {
    return nil, false
	}
	return o.RepetitionUid, true
}

// HasRepetitionUid returns a boolean if a field has been set.
func (o *Broadcast) HasRepetitionUid() bool {
	if o != nil && !isNil(o.RepetitionUid) {
		return true
	}

	return false
}

// SetRepetitionUid gets a reference to the given string and assigns it to the RepetitionUid field.
func (o *Broadcast) SetRepetitionUid(v string) {
	o.RepetitionUid = &v
}

// GetRepetitionType returns the RepetitionType field value if set, zero value otherwise.
func (o *Broadcast) GetRepetitionType() string {
	if o == nil || isNil(o.RepetitionType) {
		var ret string
		return ret
	}
	return *o.RepetitionType
}

// GetRepetitionTypeOk returns a tuple with the RepetitionType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetRepetitionTypeOk() (*string, bool) {
	if o == nil || isNil(o.RepetitionType) {
    return nil, false
	}
	return o.RepetitionType, true
}

// HasRepetitionType returns a boolean if a field has been set.
func (o *Broadcast) HasRepetitionType() bool {
	if o != nil && !isNil(o.RepetitionType) {
		return true
	}

	return false
}

// SetRepetitionType gets a reference to the given string and assigns it to the RepetitionType field.
func (o *Broadcast) SetRepetitionType(v string) {
	o.RepetitionType = &v
}

// GetRepetitionEnd returns the RepetitionEnd field value if set, zero value otherwise.
func (o *Broadcast) GetRepetitionEnd() time.Time {
	if o == nil || isNil(o.RepetitionEnd) {
		var ret time.Time
		return ret
	}
	return *o.RepetitionEnd
}

// GetRepetitionEndOk returns a tuple with the RepetitionEnd field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetRepetitionEndOk() (*time.Time, bool) {
	if o == nil || isNil(o.RepetitionEnd) {
    return nil, false
	}
	return o.RepetitionEnd, true
}

// HasRepetitionEnd returns a boolean if a field has been set.
func (o *Broadcast) HasRepetitionEnd() bool {
	if o != nil && !isNil(o.RepetitionEnd) {
		return true
	}

	return false
}

// SetRepetitionEnd gets a reference to the given time.Time and assigns it to the RepetitionEnd field.
func (o *Broadcast) SetRepetitionEnd(v time.Time) {
	o.RepetitionEnd = &v
}

// GetRepetitionStart returns the RepetitionStart field value if set, zero value otherwise.
func (o *Broadcast) GetRepetitionStart() time.Time {
	if o == nil || isNil(o.RepetitionStart) {
		var ret time.Time
		return ret
	}
	return *o.RepetitionStart
}

// GetRepetitionStartOk returns a tuple with the RepetitionStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetRepetitionStartOk() (*time.Time, bool) {
	if o == nil || isNil(o.RepetitionStart) {
    return nil, false
	}
	return o.RepetitionStart, true
}

// HasRepetitionStart returns a boolean if a field has been set.
func (o *Broadcast) HasRepetitionStart() bool {
	if o != nil && !isNil(o.RepetitionStart) {
		return true
	}

	return false
}

// SetRepetitionStart gets a reference to the given time.Time and assigns it to the RepetitionStart field.
func (o *Broadcast) SetRepetitionStart(v time.Time) {
	o.RepetitionStart = &v
}

// GetRepetitionDays returns the RepetitionDays field value if set, zero value otherwise.
func (o *Broadcast) GetRepetitionDays() string {
	if o == nil || isNil(o.RepetitionDays) {
		var ret string
		return ret
	}
	return *o.RepetitionDays
}

// GetRepetitionDaysOk returns a tuple with the RepetitionDays field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetRepetitionDaysOk() (*string, bool) {
	if o == nil || isNil(o.RepetitionDays) {
    return nil, false
	}
	return o.RepetitionDays, true
}

// HasRepetitionDays returns a boolean if a field has been set.
func (o *Broadcast) HasRepetitionDays() bool {
	if o != nil && !isNil(o.RepetitionDays) {
		return true
	}

	return false
}

// SetRepetitionDays gets a reference to the given string and assigns it to the RepetitionDays field.
func (o *Broadcast) SetRepetitionDays(v string) {
	o.RepetitionDays = &v
}

// GetPtyCodeId returns the PtyCodeId field value if set, zero value otherwise.
func (o *Broadcast) GetPtyCodeId() int64 {
	if o == nil || isNil(o.PtyCodeId) {
		var ret int64
		return ret
	}
	return *o.PtyCodeId
}

// GetPtyCodeIdOk returns a tuple with the PtyCodeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetPtyCodeIdOk() (*int64, bool) {
	if o == nil || isNil(o.PtyCodeId) {
    return nil, false
	}
	return o.PtyCodeId, true
}

// HasPtyCodeId returns a boolean if a field has been set.
func (o *Broadcast) HasPtyCodeId() bool {
	if o != nil && !isNil(o.PtyCodeId) {
		return true
	}

	return false
}

// SetPtyCodeId gets a reference to the given int64 and assigns it to the PtyCodeId field.
func (o *Broadcast) SetPtyCodeId(v int64) {
	o.PtyCodeId = &v
}

// GetPlannedInEpg returns the PlannedInEpg field value if set, zero value otherwise.
func (o *Broadcast) GetPlannedInEpg() int32 {
	if o == nil || isNil(o.PlannedInEpg) {
		var ret int32
		return ret
	}
	return *o.PlannedInEpg
}

// GetPlannedInEpgOk returns a tuple with the PlannedInEpg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetPlannedInEpgOk() (*int32, bool) {
	if o == nil || isNil(o.PlannedInEpg) {
    return nil, false
	}
	return o.PlannedInEpg, true
}

// HasPlannedInEpg returns a boolean if a field has been set.
func (o *Broadcast) HasPlannedInEpg() bool {
	if o != nil && !isNil(o.PlannedInEpg) {
		return true
	}

	return false
}

// SetPlannedInEpg gets a reference to the given int32 and assigns it to the PlannedInEpg field.
func (o *Broadcast) SetPlannedInEpg(v int32) {
	o.PlannedInEpg = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *Broadcast) GetGroupId() int64 {
	if o == nil || isNil(o.GroupId) {
		var ret int64
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Broadcast) GetGroupIdOk() (*int64, bool) {
	if o == nil || isNil(o.GroupId) {
    return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *Broadcast) HasGroupId() bool {
	if o != nil && !isNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given int64 and assigns it to the GroupId field.
func (o *Broadcast) SetGroupId(v int64) {
	o.GroupId = &v
}

func (o Broadcast) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ProgramId) {
		toSerialize["program_id"] = o.ProgramId
	}
	if !isNil(o.ModelTypeId) {
		toSerialize["model_type_id"] = o.ModelTypeId
	}
	if !isNil(o.StationId) {
		toSerialize["station_id"] = o.StationId
	}
	if !isNil(o.FieldValues) {
		toSerialize["field_values"] = o.FieldValues
	}
	if !isNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !isNil(o.Start) {
		toSerialize["start"] = o.Start
	}
	if !isNil(o.Stop) {
		toSerialize["stop"] = o.Stop
	}
	if !isNil(o.GenreId) {
		toSerialize["genre_id"] = o.GenreId
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !isNil(o.ShortName) {
		toSerialize["short_name"] = o.ShortName
	}
	if !isNil(o.MediumName) {
		toSerialize["medium_name"] = o.MediumName
	}
	if !isNil(o.Website) {
		toSerialize["website"] = o.Website
	}
	if !isNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !isNil(o.Recommended) {
		toSerialize["recommended"] = o.Recommended
	}
	if !isNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	if !isNil(o.Published) {
		toSerialize["published"] = o.Published
	}
	if !isNil(o.RepetitionUid) {
		toSerialize["repetition_uid"] = o.RepetitionUid
	}
	if !isNil(o.RepetitionType) {
		toSerialize["repetition_type"] = o.RepetitionType
	}
	if !isNil(o.RepetitionEnd) {
		toSerialize["repetition_end"] = o.RepetitionEnd
	}
	if !isNil(o.RepetitionStart) {
		toSerialize["repetition_start"] = o.RepetitionStart
	}
	if !isNil(o.RepetitionDays) {
		toSerialize["repetition_days"] = o.RepetitionDays
	}
	if !isNil(o.PtyCodeId) {
		toSerialize["pty_code_id"] = o.PtyCodeId
	}
	if !isNil(o.PlannedInEpg) {
		toSerialize["planned_in_epg"] = o.PlannedInEpg
	}
	if !isNil(o.GroupId) {
		toSerialize["group_id"] = o.GroupId
	}
	return json.Marshal(toSerialize)
}

type NullableBroadcast struct {
	value *Broadcast
	isSet bool
}

func (v NullableBroadcast) Get() *Broadcast {
	return v.value
}

func (v *NullableBroadcast) Set(val *Broadcast) {
	v.value = val
	v.isSet = true
}

func (v NullableBroadcast) IsSet() bool {
	return v.isSet
}

func (v *NullableBroadcast) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBroadcast(val *Broadcast) *NullableBroadcast {
	return &NullableBroadcast{value: val, isSet: true}
}

func (v NullableBroadcast) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBroadcast) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


