/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package radiomanagerclient
// BroadcastRelationsItems struct for BroadcastRelationsItems
type BroadcastRelationsItems struct {
	Href string `json:"href,omitempty"`
	Model string `json:"model,omitempty"`
	Operation string `json:"operation,omitempty"`
	Params BroadcastRelationsItemsParams `json:"params,omitempty"`
}
