/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package radiomanagerclient
// InlineResponse202 struct for InlineResponse202
type InlineResponse202 struct {
	Success bool `json:"success,omitempty"`
}
