/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package radiomanagerclient
// BlockRelationsItemsParams struct for BlockRelationsItemsParams
type BlockRelationsItemsParams struct {
	BlockId int32 `json:"block_id,omitempty"`
}
