/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package radiomanagerclient
import (
	"time"
)
// InlineObject2 struct for InlineObject2
type InlineObject2 struct {
	Start time.Time `json:"start,omitempty"`
	AllowPlaylistPast int32 `json:"allow_playlist_past,omitempty"`
	BeforeId int32 `json:"before_id,omitempty"`
	PreviousId int32 `json:"previous_id,omitempty"`
	Items []ImportItem `json:"items,omitempty"`
}
