/*
RadioManager

This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

API version: 2.0
Contact: support@pluxbox.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package radiomanagerclient

import (
	"encoding/json"
)

// ProgramRelationsItemsParams struct for ProgramRelationsItemsParams
type ProgramRelationsItemsParams struct {
	ProgramId *int32 `json:"program_id,omitempty"`
}

// NewProgramRelationsItemsParams instantiates a new ProgramRelationsItemsParams object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProgramRelationsItemsParams() *ProgramRelationsItemsParams {
	this := ProgramRelationsItemsParams{}
	return &this
}

// NewProgramRelationsItemsParamsWithDefaults instantiates a new ProgramRelationsItemsParams object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProgramRelationsItemsParamsWithDefaults() *ProgramRelationsItemsParams {
	this := ProgramRelationsItemsParams{}
	return &this
}

// GetProgramId returns the ProgramId field value if set, zero value otherwise.
func (o *ProgramRelationsItemsParams) GetProgramId() int32 {
	if o == nil || isNil(o.ProgramId) {
		var ret int32
		return ret
	}
	return *o.ProgramId
}

// GetProgramIdOk returns a tuple with the ProgramId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProgramRelationsItemsParams) GetProgramIdOk() (*int32, bool) {
	if o == nil || isNil(o.ProgramId) {
    return nil, false
	}
	return o.ProgramId, true
}

// HasProgramId returns a boolean if a field has been set.
func (o *ProgramRelationsItemsParams) HasProgramId() bool {
	if o != nil && !isNil(o.ProgramId) {
		return true
	}

	return false
}

// SetProgramId gets a reference to the given int32 and assigns it to the ProgramId field.
func (o *ProgramRelationsItemsParams) SetProgramId(v int32) {
	o.ProgramId = &v
}

func (o ProgramRelationsItemsParams) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ProgramId) {
		toSerialize["program_id"] = o.ProgramId
	}
	return json.Marshal(toSerialize)
}

type NullableProgramRelationsItemsParams struct {
	value *ProgramRelationsItemsParams
	isSet bool
}

func (v NullableProgramRelationsItemsParams) Get() *ProgramRelationsItemsParams {
	return v.value
}

func (v *NullableProgramRelationsItemsParams) Set(val *ProgramRelationsItemsParams) {
	v.value = val
	v.isSet = true
}

func (v NullableProgramRelationsItemsParams) IsSet() bool {
	return v.isSet
}

func (v *NullableProgramRelationsItemsParams) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProgramRelationsItemsParams(val *ProgramRelationsItemsParams) *NullableProgramRelationsItemsParams {
	return &NullableProgramRelationsItemsParams{value: val, isSet: true}
}

func (v NullableProgramRelationsItemsParams) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProgramRelationsItemsParams) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


