/*
RadioManager

This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

API version: 2.0
Contact: support@pluxbox.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package radiomanagerclient

import (
	"encoding/json"
)

// CampaignTemplateItemAllOf struct for CampaignTemplateItemAllOf
type CampaignTemplateItemAllOf struct {
	ModelTypeId *int64 `json:"model_type_id,omitempty"`
	ExternalId *string `json:"external_id,omitempty"`
	FieldValues map[string]interface{} `json:"field_values,omitempty"`
	Title *string `json:"title,omitempty"`
	Duration *int64 `json:"duration,omitempty"`
	Recommended *bool `json:"recommended,omitempty"`
	StaticStart *bool `json:"static_start,omitempty"`
	Deltas map[string]interface{} `json:"_deltas,omitempty"`
}

// NewCampaignTemplateItemAllOf instantiates a new CampaignTemplateItemAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCampaignTemplateItemAllOf() *CampaignTemplateItemAllOf {
	this := CampaignTemplateItemAllOf{}
	return &this
}

// NewCampaignTemplateItemAllOfWithDefaults instantiates a new CampaignTemplateItemAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCampaignTemplateItemAllOfWithDefaults() *CampaignTemplateItemAllOf {
	this := CampaignTemplateItemAllOf{}
	return &this
}

// GetModelTypeId returns the ModelTypeId field value if set, zero value otherwise.
func (o *CampaignTemplateItemAllOf) GetModelTypeId() int64 {
	if o == nil || isNil(o.ModelTypeId) {
		var ret int64
		return ret
	}
	return *o.ModelTypeId
}

// GetModelTypeIdOk returns a tuple with the ModelTypeId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplateItemAllOf) GetModelTypeIdOk() (*int64, bool) {
	if o == nil || isNil(o.ModelTypeId) {
    return nil, false
	}
	return o.ModelTypeId, true
}

// HasModelTypeId returns a boolean if a field has been set.
func (o *CampaignTemplateItemAllOf) HasModelTypeId() bool {
	if o != nil && !isNil(o.ModelTypeId) {
		return true
	}

	return false
}

// SetModelTypeId gets a reference to the given int64 and assigns it to the ModelTypeId field.
func (o *CampaignTemplateItemAllOf) SetModelTypeId(v int64) {
	o.ModelTypeId = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *CampaignTemplateItemAllOf) GetExternalId() string {
	if o == nil || isNil(o.ExternalId) {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplateItemAllOf) GetExternalIdOk() (*string, bool) {
	if o == nil || isNil(o.ExternalId) {
    return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *CampaignTemplateItemAllOf) HasExternalId() bool {
	if o != nil && !isNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *CampaignTemplateItemAllOf) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetFieldValues returns the FieldValues field value if set, zero value otherwise.
func (o *CampaignTemplateItemAllOf) GetFieldValues() map[string]interface{} {
	if o == nil || isNil(o.FieldValues) {
		var ret map[string]interface{}
		return ret
	}
	return o.FieldValues
}

// GetFieldValuesOk returns a tuple with the FieldValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplateItemAllOf) GetFieldValuesOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.FieldValues) {
    return map[string]interface{}{}, false
	}
	return o.FieldValues, true
}

// HasFieldValues returns a boolean if a field has been set.
func (o *CampaignTemplateItemAllOf) HasFieldValues() bool {
	if o != nil && !isNil(o.FieldValues) {
		return true
	}

	return false
}

// SetFieldValues gets a reference to the given map[string]interface{} and assigns it to the FieldValues field.
func (o *CampaignTemplateItemAllOf) SetFieldValues(v map[string]interface{}) {
	o.FieldValues = v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *CampaignTemplateItemAllOf) GetTitle() string {
	if o == nil || isNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplateItemAllOf) GetTitleOk() (*string, bool) {
	if o == nil || isNil(o.Title) {
    return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *CampaignTemplateItemAllOf) HasTitle() bool {
	if o != nil && !isNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *CampaignTemplateItemAllOf) SetTitle(v string) {
	o.Title = &v
}

// GetDuration returns the Duration field value if set, zero value otherwise.
func (o *CampaignTemplateItemAllOf) GetDuration() int64 {
	if o == nil || isNil(o.Duration) {
		var ret int64
		return ret
	}
	return *o.Duration
}

// GetDurationOk returns a tuple with the Duration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplateItemAllOf) GetDurationOk() (*int64, bool) {
	if o == nil || isNil(o.Duration) {
    return nil, false
	}
	return o.Duration, true
}

// HasDuration returns a boolean if a field has been set.
func (o *CampaignTemplateItemAllOf) HasDuration() bool {
	if o != nil && !isNil(o.Duration) {
		return true
	}

	return false
}

// SetDuration gets a reference to the given int64 and assigns it to the Duration field.
func (o *CampaignTemplateItemAllOf) SetDuration(v int64) {
	o.Duration = &v
}

// GetRecommended returns the Recommended field value if set, zero value otherwise.
func (o *CampaignTemplateItemAllOf) GetRecommended() bool {
	if o == nil || isNil(o.Recommended) {
		var ret bool
		return ret
	}
	return *o.Recommended
}

// GetRecommendedOk returns a tuple with the Recommended field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplateItemAllOf) GetRecommendedOk() (*bool, bool) {
	if o == nil || isNil(o.Recommended) {
    return nil, false
	}
	return o.Recommended, true
}

// HasRecommended returns a boolean if a field has been set.
func (o *CampaignTemplateItemAllOf) HasRecommended() bool {
	if o != nil && !isNil(o.Recommended) {
		return true
	}

	return false
}

// SetRecommended gets a reference to the given bool and assigns it to the Recommended field.
func (o *CampaignTemplateItemAllOf) SetRecommended(v bool) {
	o.Recommended = &v
}

// GetStaticStart returns the StaticStart field value if set, zero value otherwise.
func (o *CampaignTemplateItemAllOf) GetStaticStart() bool {
	if o == nil || isNil(o.StaticStart) {
		var ret bool
		return ret
	}
	return *o.StaticStart
}

// GetStaticStartOk returns a tuple with the StaticStart field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplateItemAllOf) GetStaticStartOk() (*bool, bool) {
	if o == nil || isNil(o.StaticStart) {
    return nil, false
	}
	return o.StaticStart, true
}

// HasStaticStart returns a boolean if a field has been set.
func (o *CampaignTemplateItemAllOf) HasStaticStart() bool {
	if o != nil && !isNil(o.StaticStart) {
		return true
	}

	return false
}

// SetStaticStart gets a reference to the given bool and assigns it to the StaticStart field.
func (o *CampaignTemplateItemAllOf) SetStaticStart(v bool) {
	o.StaticStart = &v
}

// GetDeltas returns the Deltas field value if set, zero value otherwise.
func (o *CampaignTemplateItemAllOf) GetDeltas() map[string]interface{} {
	if o == nil || isNil(o.Deltas) {
		var ret map[string]interface{}
		return ret
	}
	return o.Deltas
}

// GetDeltasOk returns a tuple with the Deltas field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CampaignTemplateItemAllOf) GetDeltasOk() (map[string]interface{}, bool) {
	if o == nil || isNil(o.Deltas) {
    return map[string]interface{}{}, false
	}
	return o.Deltas, true
}

// HasDeltas returns a boolean if a field has been set.
func (o *CampaignTemplateItemAllOf) HasDeltas() bool {
	if o != nil && !isNil(o.Deltas) {
		return true
	}

	return false
}

// SetDeltas gets a reference to the given map[string]interface{} and assigns it to the Deltas field.
func (o *CampaignTemplateItemAllOf) SetDeltas(v map[string]interface{}) {
	o.Deltas = v
}

func (o CampaignTemplateItemAllOf) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.ModelTypeId) {
		toSerialize["model_type_id"] = o.ModelTypeId
	}
	if !isNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	if !isNil(o.FieldValues) {
		toSerialize["field_values"] = o.FieldValues
	}
	if !isNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !isNil(o.Duration) {
		toSerialize["duration"] = o.Duration
	}
	if !isNil(o.Recommended) {
		toSerialize["recommended"] = o.Recommended
	}
	if !isNil(o.StaticStart) {
		toSerialize["static_start"] = o.StaticStart
	}
	if !isNil(o.Deltas) {
		toSerialize["_deltas"] = o.Deltas
	}
	return json.Marshal(toSerialize)
}

type NullableCampaignTemplateItemAllOf struct {
	value *CampaignTemplateItemAllOf
	isSet bool
}

func (v NullableCampaignTemplateItemAllOf) Get() *CampaignTemplateItemAllOf {
	return v.value
}

func (v *NullableCampaignTemplateItemAllOf) Set(val *CampaignTemplateItemAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableCampaignTemplateItemAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableCampaignTemplateItemAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCampaignTemplateItemAllOf(val *CampaignTemplateItemAllOf) *NullableCampaignTemplateItemAllOf {
	return &NullableCampaignTemplateItemAllOf{value: val, isSet: true}
}

func (v NullableCampaignTemplateItemAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCampaignTemplateItemAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


