/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package radiomanagerclient
// CampaignRelationsItemsParams struct for CampaignRelationsItemsParams
type CampaignRelationsItemsParams struct {
	CampaignId int32 `json:"campaign_id,omitempty"`
}
