/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package radiomanagerclient
// InternalServerError struct for InternalServerError
type InternalServerError struct {
	// Given error (not formatted), describes the problem.
	Error string `json:"error"`
	// Assigned StatusCode, is used in order to create a relationship between Error and Response.
	StatusCode int64 `json:"statusCode"`
}
