/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package radiomanagerclient
// PresenterRelationsProgramsParams struct for PresenterRelationsProgramsParams
type PresenterRelationsProgramsParams struct {
	PresenterId int32 `json:"presenter_id,omitempty"`
}
