/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package radiomanagerclient
// StoryInputOnly struct for StoryInputOnly
type StoryInputOnly struct {
	Tags []int32 `json:"tags,omitempty"`
}
