/*
RadioManager

This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

API version: 2.0
Contact: support@pluxbox.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package radiomanagerclient

import (
	"encoding/json"
)

// InlineResponse401 struct for InlineResponse401
type InlineResponse401 struct {
	// Unauthorized
	Error *string `json:"error,omitempty"`
	// Given error, describes the problem.
	ErrorDescription *string `json:"error_description,omitempty"`
	// Corresponding HTTP Response Status Code
	StatusCode *int32 `json:"statusCode,omitempty"`
}

// NewInlineResponse401 instantiates a new InlineResponse401 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineResponse401() *InlineResponse401 {
	this := InlineResponse401{}
	return &this
}

// NewInlineResponse401WithDefaults instantiates a new InlineResponse401 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineResponse401WithDefaults() *InlineResponse401 {
	this := InlineResponse401{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *InlineResponse401) GetError() string {
	if o == nil || isNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse401) GetErrorOk() (*string, bool) {
	if o == nil || isNil(o.Error) {
    return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *InlineResponse401) HasError() bool {
	if o != nil && !isNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *InlineResponse401) SetError(v string) {
	o.Error = &v
}

// GetErrorDescription returns the ErrorDescription field value if set, zero value otherwise.
func (o *InlineResponse401) GetErrorDescription() string {
	if o == nil || isNil(o.ErrorDescription) {
		var ret string
		return ret
	}
	return *o.ErrorDescription
}

// GetErrorDescriptionOk returns a tuple with the ErrorDescription field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse401) GetErrorDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.ErrorDescription) {
    return nil, false
	}
	return o.ErrorDescription, true
}

// HasErrorDescription returns a boolean if a field has been set.
func (o *InlineResponse401) HasErrorDescription() bool {
	if o != nil && !isNil(o.ErrorDescription) {
		return true
	}

	return false
}

// SetErrorDescription gets a reference to the given string and assigns it to the ErrorDescription field.
func (o *InlineResponse401) SetErrorDescription(v string) {
	o.ErrorDescription = &v
}

// GetStatusCode returns the StatusCode field value if set, zero value otherwise.
func (o *InlineResponse401) GetStatusCode() int32 {
	if o == nil || isNil(o.StatusCode) {
		var ret int32
		return ret
	}
	return *o.StatusCode
}

// GetStatusCodeOk returns a tuple with the StatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineResponse401) GetStatusCodeOk() (*int32, bool) {
	if o == nil || isNil(o.StatusCode) {
    return nil, false
	}
	return o.StatusCode, true
}

// HasStatusCode returns a boolean if a field has been set.
func (o *InlineResponse401) HasStatusCode() bool {
	if o != nil && !isNil(o.StatusCode) {
		return true
	}

	return false
}

// SetStatusCode gets a reference to the given int32 and assigns it to the StatusCode field.
func (o *InlineResponse401) SetStatusCode(v int32) {
	o.StatusCode = &v
}

func (o InlineResponse401) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !isNil(o.ErrorDescription) {
		toSerialize["error_description"] = o.ErrorDescription
	}
	if !isNil(o.StatusCode) {
		toSerialize["statusCode"] = o.StatusCode
	}
	return json.Marshal(toSerialize)
}

type NullableInlineResponse401 struct {
	value *InlineResponse401
	isSet bool
}

func (v NullableInlineResponse401) Get() *InlineResponse401 {
	return v.value
}

func (v *NullableInlineResponse401) Set(val *InlineResponse401) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineResponse401) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineResponse401) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineResponse401(val *InlineResponse401) *NullableInlineResponse401 {
	return &NullableInlineResponse401{value: val, isSet: true}
}

func (v NullableInlineResponse401) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineResponse401) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


