/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package radiomanagerclient

type ModelTypeOutputOnly struct {

	ExternalStationId int64 `json:"_external_station_id,omitempty"`
}
