/*
RadioManager

This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.

API version: 2.0
Contact: support@pluxbox.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package radiomanagerclient

import (
	"encoding/json"
)

// BroadcastEPGRelations struct for BroadcastEPGRelations
type BroadcastEPGRelations struct {
	Items *BroadcastRelationsItems `json:"items,omitempty"`
	Blocks *BroadcastRelationsBlocks `json:"blocks,omitempty"`
	Program *BlockRelationsProgram `json:"program,omitempty"`
	Tags *BroadcastRelationsTags `json:"tags,omitempty"`
	Presenters []PresenterEPGResult `json:"presenters,omitempty"`
	ModelType *BroadcastRelationsModelType `json:"model_type,omitempty"`
}

// NewBroadcastEPGRelations instantiates a new BroadcastEPGRelations object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBroadcastEPGRelations() *BroadcastEPGRelations {
	this := BroadcastEPGRelations{}
	return &this
}

// NewBroadcastEPGRelationsWithDefaults instantiates a new BroadcastEPGRelations object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBroadcastEPGRelationsWithDefaults() *BroadcastEPGRelations {
	this := BroadcastEPGRelations{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *BroadcastEPGRelations) GetItems() BroadcastRelationsItems {
	if o == nil || isNil(o.Items) {
		var ret BroadcastRelationsItems
		return ret
	}
	return *o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BroadcastEPGRelations) GetItemsOk() (*BroadcastRelationsItems, bool) {
	if o == nil || isNil(o.Items) {
    return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *BroadcastEPGRelations) HasItems() bool {
	if o != nil && !isNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given BroadcastRelationsItems and assigns it to the Items field.
func (o *BroadcastEPGRelations) SetItems(v BroadcastRelationsItems) {
	o.Items = &v
}

// GetBlocks returns the Blocks field value if set, zero value otherwise.
func (o *BroadcastEPGRelations) GetBlocks() BroadcastRelationsBlocks {
	if o == nil || isNil(o.Blocks) {
		var ret BroadcastRelationsBlocks
		return ret
	}
	return *o.Blocks
}

// GetBlocksOk returns a tuple with the Blocks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BroadcastEPGRelations) GetBlocksOk() (*BroadcastRelationsBlocks, bool) {
	if o == nil || isNil(o.Blocks) {
    return nil, false
	}
	return o.Blocks, true
}

// HasBlocks returns a boolean if a field has been set.
func (o *BroadcastEPGRelations) HasBlocks() bool {
	if o != nil && !isNil(o.Blocks) {
		return true
	}

	return false
}

// SetBlocks gets a reference to the given BroadcastRelationsBlocks and assigns it to the Blocks field.
func (o *BroadcastEPGRelations) SetBlocks(v BroadcastRelationsBlocks) {
	o.Blocks = &v
}

// GetProgram returns the Program field value if set, zero value otherwise.
func (o *BroadcastEPGRelations) GetProgram() BlockRelationsProgram {
	if o == nil || isNil(o.Program) {
		var ret BlockRelationsProgram
		return ret
	}
	return *o.Program
}

// GetProgramOk returns a tuple with the Program field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BroadcastEPGRelations) GetProgramOk() (*BlockRelationsProgram, bool) {
	if o == nil || isNil(o.Program) {
    return nil, false
	}
	return o.Program, true
}

// HasProgram returns a boolean if a field has been set.
func (o *BroadcastEPGRelations) HasProgram() bool {
	if o != nil && !isNil(o.Program) {
		return true
	}

	return false
}

// SetProgram gets a reference to the given BlockRelationsProgram and assigns it to the Program field.
func (o *BroadcastEPGRelations) SetProgram(v BlockRelationsProgram) {
	o.Program = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *BroadcastEPGRelations) GetTags() BroadcastRelationsTags {
	if o == nil || isNil(o.Tags) {
		var ret BroadcastRelationsTags
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BroadcastEPGRelations) GetTagsOk() (*BroadcastRelationsTags, bool) {
	if o == nil || isNil(o.Tags) {
    return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *BroadcastEPGRelations) HasTags() bool {
	if o != nil && !isNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given BroadcastRelationsTags and assigns it to the Tags field.
func (o *BroadcastEPGRelations) SetTags(v BroadcastRelationsTags) {
	o.Tags = &v
}

// GetPresenters returns the Presenters field value if set, zero value otherwise.
func (o *BroadcastEPGRelations) GetPresenters() []PresenterEPGResult {
	if o == nil || isNil(o.Presenters) {
		var ret []PresenterEPGResult
		return ret
	}
	return o.Presenters
}

// GetPresentersOk returns a tuple with the Presenters field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BroadcastEPGRelations) GetPresentersOk() ([]PresenterEPGResult, bool) {
	if o == nil || isNil(o.Presenters) {
    return nil, false
	}
	return o.Presenters, true
}

// HasPresenters returns a boolean if a field has been set.
func (o *BroadcastEPGRelations) HasPresenters() bool {
	if o != nil && !isNil(o.Presenters) {
		return true
	}

	return false
}

// SetPresenters gets a reference to the given []PresenterEPGResult and assigns it to the Presenters field.
func (o *BroadcastEPGRelations) SetPresenters(v []PresenterEPGResult) {
	o.Presenters = v
}

// GetModelType returns the ModelType field value if set, zero value otherwise.
func (o *BroadcastEPGRelations) GetModelType() BroadcastRelationsModelType {
	if o == nil || isNil(o.ModelType) {
		var ret BroadcastRelationsModelType
		return ret
	}
	return *o.ModelType
}

// GetModelTypeOk returns a tuple with the ModelType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BroadcastEPGRelations) GetModelTypeOk() (*BroadcastRelationsModelType, bool) {
	if o == nil || isNil(o.ModelType) {
    return nil, false
	}
	return o.ModelType, true
}

// HasModelType returns a boolean if a field has been set.
func (o *BroadcastEPGRelations) HasModelType() bool {
	if o != nil && !isNil(o.ModelType) {
		return true
	}

	return false
}

// SetModelType gets a reference to the given BroadcastRelationsModelType and assigns it to the ModelType field.
func (o *BroadcastEPGRelations) SetModelType(v BroadcastRelationsModelType) {
	o.ModelType = &v
}

func (o BroadcastEPGRelations) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	if !isNil(o.Blocks) {
		toSerialize["blocks"] = o.Blocks
	}
	if !isNil(o.Program) {
		toSerialize["program"] = o.Program
	}
	if !isNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !isNil(o.Presenters) {
		toSerialize["presenters"] = o.Presenters
	}
	if !isNil(o.ModelType) {
		toSerialize["model_type"] = o.ModelType
	}
	return json.Marshal(toSerialize)
}

type NullableBroadcastEPGRelations struct {
	value *BroadcastEPGRelations
	isSet bool
}

func (v NullableBroadcastEPGRelations) Get() *BroadcastEPGRelations {
	return v.value
}

func (v *NullableBroadcastEPGRelations) Set(val *BroadcastEPGRelations) {
	v.value = val
	v.isSet = true
}

func (v NullableBroadcastEPGRelations) IsSet() bool {
	return v.isSet
}

func (v *NullableBroadcastEPGRelations) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBroadcastEPGRelations(val *BroadcastEPGRelations) *NullableBroadcastEPGRelations {
	return &NullableBroadcastEPGRelations{value: val, isSet: true}
}

func (v NullableBroadcastEPGRelations) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBroadcastEPGRelations) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


