/*
 * RadioManager
 *
 * RadioManager
 *
 * API version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package radiomanagerclient

type StoryRelations struct {

	Tags *StoryRelationsTags `json:"tags"`

	Items *StoryRelationsItems `json:"items,omitempty"`

	ModelType *BroadcastRelationsModelType `json:"model_type,omitempty"`
}
