/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package radiomanagerclient

// Story
type Story struct {

	ModelTypeId int64 `json:"model_type_id"`

	Recommended bool `json:"recommended,omitempty"`

	FieldValues *interface{} `json:"field_values,omitempty"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`
}
