/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package radiomanagerclient

type StoryRelations struct {

	Tags *StoryRelationsTags `json:"tags,omitempty"`

	Items *StoryRelationsItems `json:"items,omitempty"`

	ModelType *BroadcastRelationsModelType `json:"model_type,omitempty"`
}
