/* 
 * RadioManager
 *
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package radiomanagerclient

type TagRelations struct {

	Broadcasts TagRelationsBroadcasts `json:"broadcasts,omitempty"`

	Programs TagRelationsPrograms `json:"programs,omitempty"`

	Contacts TagRelationsContacts `json:"contacts,omitempty"`

	Items TagRelationsItems `json:"items,omitempty"`
}
